<?
$perspicuous_path = dirname(__FILE__);
class Config {
	public static $DbType = 'MySqlDB';
	public static $Host = 'localhost';
	public static $UserName = '';
	public static $Password = '';
	public static $Database = '';
	public static $DbObject = null;
	public static $DateFormat = 'Y-m-d';
	public static $TimeFormat = 'H:i:s';
	public static $Theme = 'halcyonic';
public static $BaseURL = '/';
public static $Live = false;
}
?>